name = "some_service"

[docker.vars]
var = "var_value"
other_var = "other_var_value"

[qa]
path = ["./test_files/manifest.yaml", "subpath"]
[qa.vars]
var1.path = ["./test_files/manifest.yaml", "subpath"]
var2.path = []
var3.path = [[], "other_subpath"]
some_var.name = "some_name"
[qa.enc.vars]
enc_var.path = "./path.enc"

# TODO example using kubernetes kustomize
[kustomize]
path = ["/Users/mkatychev/Documents/ryerson/.kubernetes/gcp/qa/pbs/kustomization.yaml", "configMapGenerator.[0].literals"]
type = "dotenv"
[kustomize.vars]
billing_db = {path = [], name = "BILLING_DB"}
billing_db_host = {path = [], name = "BILLING_DB_HOST"}
http_port = {path = [], name = "HTTP_PORT"}
