name = "basic_service"

# key value pairs for a context are defined under <ctx>.vars
[docker.vars]
var = "var_value"
other_var = "other_var_value"

[sops]
# a default path to be inherited can be defined under <ctx>.path
path = ["./test_files/manifest.yaml", "subpath"]
[sops.vars]
# a <var>.path key can map to four valid types:
# 1. path value is "string_value" - indicating a single file to look through
# 2. path value is [] - thus <ctx>.path will be inherited
# 3. path value is a ["two_index, "array"] - either index being [] or "string_value":
# -  [[], "subpath"] - path will be inherited from <ctx>.path if present
# -  ["path", []] - subpath will be inherited from <ctx>.path if present
# 4. ["path", "subpath"] - nothing will be inherited
var1.path = ["./test_files/manifest.yaml", "subpath"]
var2.path = []
var3.path = [[], "other_subpath"]
# dangling variable should return {"some_var": ""} since only name override was defined
some_var.name = "some_name" 
# key value pairs for an encrypted context are defined under <ctx>.enc.vars
[sops.enc.vars]
enc_var.path = "./test_files/test.enc.yaml"

[kustomize]
path = ["./test_files/kustomization.yaml", "configMapGenerator.[0].literals"]
# a default deserialization path to be inherited can be defined under <ctx>.path
# once <var>.path has been traversed, attempt to deserialize the returned object
# as if it was in dotenv format
type = "dotenv"
[kustomize.vars]
# var1.name = "VAR_1" means that the key alias "VAR_1" will
# be searched for to retrieve the var1 value
var1 = {path = [], name = "VAR_1"}
var2 = {path = [], name = "VAR_2"}
json_var = {path = [[], "jsonMap"], type = "json", name = "VAR_3"}

[flat_json]
path = ["./test_files/json_map.json", "valid_flat_map"]
[flat_json.vars]
var1.path = []
var2.path = []
var3.path = []
var4.path = [[], "var4_complex.nested"]

[complex_json]
path = ["./test_files/json_map.json", "valid_flat_map"]
[complex_json.vars]
var1.path = []
var2.path = []
var3.path = []
# '[[], ""]' retains "./test_files/json_map.json" in [] reference in index 0
# and "" in index 1 disables object traversal
var4 = {path = [[], ""], name = "var4_complex", type = "json{}"}
# returns file in entirety as value for k/v pair
entire_file = {path = [[], ""], type = "whole"}

