name = "some_service"

[docker]
var = "var_value"
other_var = "other_var_value"
[qa]
var.path = ["./test_files/manifest.yaml", "subpath"]
other_var.path = ["./test_files/manifest.yaml", "subpath"]
some_var.name = "some_name"
[qa.enc]
enc_var.path = "./test_files/test.enc.yaml"
