name = "some_service"

[docker.vars]
var = "var_value"
other_var = "other_var_value"

[qa]
path = ["./test_files/manifest.yaml", "subpath"]
[qa.vars]
var1.path = ["./test_files/manifest.yaml", "subpath"]
var2.path = []
var3.path = [[], "other_subpath"]
some_var.name = "some_name" #dangling variable should return {"some_var": ""} since only name override was defined
[qa.enc.vars]
enc_var.path = "./test_files/test.enc.yaml"

[kustomize]
path = ["./test_files/kustomization.yaml", "configMapGenerator.[0].literals"]
type = "dotenv"
[kustomize.vars]
var1 = {path = [], name = "VAR_1"}
var2 = {path = [], name = "VAR_2"}
