service_name = 'some_service'

# https://toml.io/en/v1.0.0-rc.1#section-18
# env = 'docker'
[[docker]]

[[docker.cfg]]
[docker.cfg.var]
value = 'var_value'

[[docker.cfg]]
[docker.cfg.other_var]
value = 'other_var_value'

# docker.enc & docker.cfg indicates the division between cfgtext configs and encrypted ones
[[docker.enc]]
[docker.enc.enc_var]
path = 'path/to/file.enc.yaml'

# env = 'qa'
[[qa]]

[[qa.cfg]]
[qa.cfg.var]
name = 'VAR_NAME'
path = 'path/to/qa/prefs.yaml'
# traverse 'path/to/qa/file.enc.yaml' in yq style if file is not a flat structure:
sub_path = '.config.enc_var_name'

[[qa.enc]]
[qa.enc.enc_var]
name = 'ENC_VAR_NAME'
path = 'path/to/qa/file.enc.yaml'
