name = "remote configs"

# GET is the default request type
[get.vars]
# if the file path is a valid URL, then an HTTP request will be made to try to retrieve the file
core-js.path = [ "https://raw.githubusercontent.com/facebook/react/master/package.json", ".devDependencies"]
hardcoded_val = "val"

# https://httpbin.org/#/HTTP_Methods/post_post
[post]
header.accept = "application/json"
method = "POST"
path = "https://httpbin.org/post"
[post.vars]
origin.path = []
User-Agent.path = [[], ".headers"]

# TODO implement global body for the same path
[post_body.vars]
data = {
	header.accept = "application/json",
	method = "POST",
	path = "https://httpbin.org/post",
	body = "\"THIS IS THE BODY\"",
	header.accept = "application/json"
}
