configMapGenerator:
  - name: basic-environment
    literals:
      - VAR_1=var1_value
      - VAR_2=var2_value
      - >-
        SOME_MULTILINE_JSON={
         "some_key": "some_value",
        }
jsonMap: { "var3": "var3_value" }
complexJsonMap: |
  {
    "complex_var": {
      "nested": ["value", "value"]
    }
  }
