on: pull_request
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: unit
      run: go test ./...
  integration-test:
    strategy:
      matrix:
        out: [json, toml, yaml, dotenv, raw]
        cog:
          - "docker basic.cog.toml"
          - "sops basic.cog.toml"
          - "kustomize basic.cog.toml"
          - "inheritor advanced.cog.toml"
          - "flat_json advanced.cog.toml"
          - "complex_json advanced.cog.toml"
          - "envsubst envsubst.cog.toml"
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Import GPG Key
      run: gpg --import ./test_files/sops_functional_tests_key.asc
    - name: gen docker
      run: go run ./cmd/cogs ${{ matrix.cog }} --out=${{ matrix.out }}
    - name: gen ${{ matrix.cog }}
